version: '3'
services:
  php-apache:
    image: ${RUN_IMAGE}-${PHP_VERSION}:${IMAGE_TAG}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        PHP_VERSION: ${PHP_VERSION}
